import { AuthProvider } from "@contexts";
import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { Tooltip } from "radix-ui";
import { Bounce, ToastContainer } from "react-toastify";
import { inter } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Theme>
          <NextIntlClientProvider>
            <Tooltip.Provider>
              <AuthProvider>{children}</AuthProvider>
              <ToastContainer
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick={false}
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
                transition={Bounce}
              />
            </Tooltip.Provider>
          </NextIntlClientProvider>
        </Theme>
      </body>
    </html>
  );
}
