import type { Metadata } from "next";
import { inter } from "./font";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { AuthProvider } from "@contexts";
import { Tooltip } from "radix-ui";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Theme>
          <NextIntlClientProvider>
            <Tooltip.Provider>
              <AuthProvider>{children}</AuthProvider>
            </Tooltip.Provider>
          </NextIntlClientProvider>
        </Theme>
      </body>
    </html>
  );
}
